
@startuml userRegistration

left header
<font color=000 size=18><b>Package:</b> Analyst

<font color=000 size=16><b>ID:</b> UC-2
<font color=000 size=16><b>Назва:</b> Інструменти для аналізу даних.
<font color=000 size=16><b>Учасники:</b> Користувач, Система.
<font color=000 size=16><b>Передумови:</b> Аналітики можуть використовувати функції для аналізу даних, щоб давати оцінку опитуванням.
<font color=000 size=16><b>Результат:</b> Отримані дані будуть використовуватись в подальших етапах роботи аналітика.
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
:Аналітик переходить в режим перегляду (UC1).;

:Обирає потрібне йому представлення результатів.;

:Можливість сотувати, обирати порядок (закономірніть) показу даних у вкладці 
"Категорії" за зростанням/спаданням, або ж самому задати порядок.;

|Користувач|

: Користувач може сам обрати режим перегляду в меню "Представлення";
 note right #aaffaa

end note

:Можливість поєднувати або видаляти пункти 
відповідей, ставлячи галочки перед певними їх варіантами.;

:Зміна кольорів діаграм (у відповідних формах).;

:Масштабування зображешь.;

:Можливість для формату JSON скопіювати дані в буфер обміну, натиснувши на 
кнопку "Скопіювати", або завантажити зразу готовий файл (кнопка "Завантажити").;
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml