@startuml userRegistration

left header
<font color=000 size=18><b>Package:</b> Guest

<font color=000 size=16><b>ID:</b> UC-2
<font color=000 size=16><b>Назва:</b> Регістрація нового користувача.
<font color=000 size=16><b>Учасники:</b> Гість, Система.
<font color=000 size=16><b>Передумови:</b> Користувач отримав посилання на анонімне опитування в, наприклад, соціальній мережі.
<font color=000 size=16><b>Результат:</b> Дані, вказані гостем у анкеті, записані до бази даних, гість отримав  
<font color=000 size=16>                       свої відповіді на пошту, якщо вказав її.

<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Такої пошти не існує
<font color=000 size=16> EX_01: Доступ до бази даних відсутній

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Гість переходить за посиланням.;
|Система|
: Система надає користувачу унікальний ідентифікатор та анкету;
note right #aaffaa

Унікальний ідентифікатор потрібен для того щоб
відрізняти гостей один від одного, та у тому випадку, 
якщо гість захочу зареєструватися. Гість не бачить
унікальний ідентифікатор.

end note

|Користувач|

: Користувач заповнює анкету, та опціонально
 залишає свою пошту для того, щоб отримати свої відповіді.
 Натискає кнопку "Надіслати".;

|Система|

: Зберігає дані у базі даних, надсилає копію анкети на вказану пошту.;
note right #aaffaa

<font color=red><b> Можливо EX_00.
<font color=red><b> Можливо EX_01.

end note

|Користувач|
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml