 @startuml Analysis Tools
left header
<font color=000 size=18><b>Package:</b> Analyst

<font color=000 size=16><b>ID:</b> UC-2
<font color=000 size=16><b>Назва:</b> Використання інструментів.
<font color=000 size=16><b>Учасники:</b> Аналітик, Система.
<font color=000 size=16><b>Передумови:</b> Наявність даних.
<font color=000 size=16><b>Результат:</b> Отримані дані будуть використовуватись в подальших етапах роботи аналітика.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Збій доступу до БД
<font color=000 size=16> EX_01: Помилки при вилученні даних з БД

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Аналітик переходить в режим перегляду;

: Обирає потрібне йому представлення результатів;

|Система|
: Система дає можливість сортувати, обирати порядок
  (закономірніть) показу даних у вкладці "Категорії"
  за зростанням/спаданням, або ж самому задати порядок;

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note


: Можливість поєднувати або видаляти пункти відповідей,
  ставлячи галочки перед певними їх варіантами;

: Зміна кольорів діаграм (у відповідних формах);

: Масштабування зображешь;

|Користувач|
: Аналалітик, натиснувши на кнопку "Скопіювати", або
  завантажує зразу готовий файл (кнопка "Завантажити");

|Система|
: Можливість для формату JSON скопіювати дані в
  буфер обміну, натиснувши на кнопку "Скопіювати",
  або завантажити зразу готовий файл (кнопка
  "Завантажити");

note right #aaffaa
<font color=red><b> Можливо EX_01.
end note


|Користувач|
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
