 @startuml Prognoses Mechanisms
left header
<font color=000 size=18><b>Package:</b> Analyst

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Статистичні механізми для прогнозування відповідей.
<font color=000 size=16><b>Учасники:</b> Аналітик, Система.
<font color=000 size=16><b>Передумови:</b> Аналітики на основі наданих відповіей (їх кількості) складають прогноз 
<font color=000 size=16> можливих результатів опитуваня (опитувань) в визнечені періоди (день\тиждень\місяць\рік).
<font color=000 size=16><b>Результат:</b> Графік теперішніх відповідей та аналатичного прогнозу за певний час.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Аналітик натискає кнопку "Прогнозування";

|Система|
: Система відкриває сторінку прогнозування;

|Користувач|
: Аналітик отримує пусту (за замовчуванням) вкладку;

: Серед меню "Прогнозувати на..." обирається термін та
      кількіть одиниць відліку (днів, тижнів та ін.);

|Система|
: Система будує прогноз за відповідним запитом на
  основі вже наявних результатів опитувань - це
  графік залежності одиниць часу та кількості відповідей;

|Користувач|
: Дане графічне зображення аналітик може
    завантажити (кножка "Завантажити");

|Система|
: Система завантажує згенерований прогноз;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
