 @startuml Reports Forming
left header
<font color=000 size=18><b>Package:</b> Analyst

<font color=000 size=16><b>ID:</b> UC-4
<font color=000 size=16><b>Назва:</b> Формування звітності.
<font color=000 size=16><b>Учасники:</b> Аналітик, Система.
<font color=000 size=16><b>Передумови:</b> Аналітики мають доступ до результатів опитувань, можуть переглядати їх.
<font color=000 size=16><b>Результат:</b> Дані анкетування надаються у файлі формату документу, де вказані результати анетувань.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Аналітик напискає кнопку "Сформувати звіт";

|Система|
: Система відкриває вкладку, де обираються
      анкетування, які входять у звіт;

|Користувач|
: Аналітик обирає представлення і сортування
  відповідей (у відповідних списках - меню);

|Система|
: Система реагує на вхідні параметри;

|Користувач|
: Після вибору потрібних анкет і параметрів
аналітик натискае книпку "Далі (створити звіт)";

|Система|
: На основі даних система створює документ;

|Користувач|
: Надається згенерований документ, в якому
сформована титульна стовінка та пункти
      опитувань (їх представлення);

|Система|
: Документ можна зберегти (в форматах .docx, .pdf, ...);

|Користувач|
: Аналітик завантажує документ;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
