@startuml userTariffs
left header
<font color=000 size=18><b>Package:</b> User

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Зміна тарифного плану користувачем.
<font color=000 size=16><b>Учасники:</b> Користувач-респондент, Система.
<font color=000 size=16><b>Передумови:</b> Користувач має бути авторизований в системі.
<font color=000 size=16><b>Результат:</b> Користувач отримує доступ до можливостей і функіціоналу відповідно до тарифу, який він обрав.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Система не отримала підтвердження про успішну оплату
<font color=000 size=16> EX_01: Оплата не була проведена впродовж відведеного періоду

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач переходить до розділу "Тарифи";

|Система|
:    Система надає форму, з інформацією про всі наявні 
     тарифні плани що дозволяють розширити можливості 
   його облікового запису (під розширенням можливостей 
   мається на увазі підключення режиму Інтерв’юера, а 
також додаткова можливість підключити ще й режим Аналітика);

|Користувач|

: Користувач вибирає необхідний тариф і натискає на нього;

|Система|

: Система обробляє заяву на підключення та надсилає 
        користувачу реквізити на оплату;

|Користувач|

: Користувач проводить оплату за вибраним тарифом;


|Система|

: Система отримує підтвердження про успішну оплату;
note right #aaffaa

<font color=red><b> Можливо EX_00.
<font color=red><b> Можливо EX_01.

end note

: Система відкриває користувачу доступ до можливостей його тарифного плану;

|Користувач|
: Користувач отримує можливість користуватися перевагами вибраного тарифного плану;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
