
@startuml userRegistration

left header
<font color=000 size=18><b>Package:</b> Analyst

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b>Статистичні механізми для прогнозування відповідей
<font color=000 size=16><b>Учасники:</b> Користувач, Система.
<font color=000 size=16><b>Передумови:</b> Аналітики на основі наданих відповіей (їх кількості) 
<font color=000 size=16>складають прогноз можливих результатів опитуваня (опитувань) в визнечені періоди (день\тиждень\місяць\рік).
<font color=000 size=16><b>Результат:</b> Графік теперішніх відповідей та аналатичного прогнозу за певний час.
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Аналітик натискає кнопку "Прогнозування".;

|Система|
:Система надає пусту (за замовчуванням) вкладку.;

|Користувач|

:Серед меню "Прогнозувати на..." обирається термін та кількіть 
одиниць відліку (днів. тижнів та ін.).;

|Система|
:Будується прогноз за відповідним запитом на основі вже наявних 
 результатів опитувань - це графік залежності одиниць часу та кількості відповідей.;


|Користувач|
:Дане графічне зображення можна завантажити 
 (кножка "Завантажити").;
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml