@startuml userTechSupport
left header
<font color=000 size=18><b>Package:</b> User

<font color=000 size=16><b>ID:</b> UC-4
<font color=000 size=16><b>Назва:</b> Зв'язок з техпідтримкою.
<font color=000 size=16><b>Учасники:</b> Користувач, Система.
<font color=000 size=16><b>Передумови:</b> Користувач має бути авторизований в системі.
<font color=000 size=16><b>Результат:</b> Користувач отримує відповід на задене питання. 
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Дані введено некоректно
<font color=000 size=16> EX_01: Доступ до бази даних відсутній
<font color=000 size=16> EX_02: Зв'язок з менеджером відсутній

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач заходить в розділ "Техпідтримка";

|Система|
: Система надає користувачу доступ до форми, де представлені всі 
поширені запитання. (Список даних запитань поповнюється менеджерами);

: В цій же формі, наявна кнопка "Задати інше запитання";

|Користувач|
: Користувач знаходить відповідь у списку FAQ. Якщо ж 
   там необхідної інформації немає, він натискає 
           кнопку "Задати інше запитання";
           

|Система|
: Система надає користувачу форму техпідтримки, 
    де користувач має заповнити необхідні поля;
    

|Користувач|
: Користувач заповнює форму, де вказує свою 
  електронну адресу на яку прийде відповідь, 
      тему запиту, та саме запитання;
      
: Користувач натискає кнопку «Відправити»;

|Система|

: Система перевіряє чи коректно заповнені всі поля форми;
note right #aaffaa

<font color=red><b> Можливо EX_00.

end note

: Система зберігає в базі і відправляє запит на отримання 
відповіді, а також саму форму менеджеру по роботі з клієнтами;

note right #aaffaa

<font color=red><b> Можливо EX_01.
<font color=red><b> Можливо EX_02.

end note

: Після того як менеджер оформив відповідь, він 
відсилає повідомлення на пошту яку залишив користувач.;
note right #aaffaa

<font color=red><b> Можливо EX_02.

end note

|Користувач|

: Користувач отримує відповідь на поставлене запитання;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
