 @startuml 
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Організація служб тех. підтримки.
<font color=000 size=16><b>Учасники:</b> Адмінінстратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор має зв'язок з тех. підтримкою.
<font color=000 size=16><b>Результат:</b> Адміністратов надає тех. підтримці команди та певні права доступу службі тех. підтримки.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Збій відправки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить на сторінку 
  за посиланням "Тех. підтримка";

|Система|
: Система надає необхідну сторінку;

|Користувач|
: В полі "Розпорядження" адміністратор записує
  необхідні дії та план роботи з системою;

: В списку "Надати доступ до" обирає наступні права доступа;

note left #aaffaa
  - перегляд анкет; 
  - редагування анкет;  
  - тестування анкетування; 
  - перегляд результатів та прогнозування;
end note

|Система|
: Система заповняє поля;

|Користувач|
: Адміністратор натискає кнопку "Відправити запит"
та очікує підтвердження;

|Система|
: Система відпавляє запит і підтверджує операцію
  (напис "Прийнято" поруч з кнопкою відправки);

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml

@startuml
version
@enduml