 @startuml View Modes
left header
<font color=000 size=18><b>Package:</b> Analyst

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Перегляд результатів опитувать (режими перегляду).
<font color=000 size=16><b>Учасники:</b> Аналітик, Система.
<font color=000 size=16><b>Передумови:</b> Аналітикам надається можливість переглядати відповіді з анкетувань, анадізувати їх у зручній формі.
<font color=000 size=16><b>Результат:</b> Візуалізація потрібної інформації (в залежності від режиму).

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Аналітик натискає кнопку "Перегрянути результати"
      та переходить у відповідний розділ;

|Система|
: Обрана вкладка надає дані (що беруться з БД сервісу)
        у режимі таблиці (за замовчуванням);

|Користувач|
: Користувач може сам обрати режим перегляду в меню "Представлення";

|Система|
: Меню (система) надає режими перегляду;

note right #aaffaa
  1) таблиця - обирається за замовчуванням;
  представляє дані у формі таблиці (таблиць),
  яка містить відповідності полів запитань та
  полів кількості відповідей серед можливих
  віріантів відповідей; 

  2) стовпчикові діаграми - графічне представлення
  кіькості (або відсотків) користувачів, які дали
  певну відповідь під час опитування;  

  3) кругові діаграми - представлення відношення
  між кількістю відповідей у колі, де кожна 
  відповідь займае певну частину кола;
end note

: Система візуалізує обраний режим;

|Користувач|
: Аналітик може зберегти дані (скопіювати тект,
      завантажити зображення діаграм);

|Система|
: Система надає дані (або копіює текс в буфер
        обміну, або завантажує файл);

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
