@startuml

left header
<font color=000 size=18><b>Package:</b> Guest

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Регістрація нового користувача.
<font color=000 size=16><b>Учасники:</b> Гість, Система.
<font color=000 size=16><b>Передумови:</b> До цього даний користувач не був зареєстрований.
<font color=000 size=16><b>Результат:</b> Обліковий запис користувача створено.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Користувач с такими даними вже існує
<font color=000 size=16> EX_01: Такої пошти не існує
<font color=000 size=16> EX_02: Паролі не збігаються
<font color=000 size=16> EX_03: Не усі поля були заповнені
<font color=000 size=16> EX_04: Створення облікового запису не було 
<font color=000 size=16>               підтвержено впродовж доби 
<font color=000 size=16> EX_05: Доступ до бази даних відсутній

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Гість натискає кнопку "Зареєструватися";
|Система|
: Система отримує ідентифікатор гостя та надсилає форму реєстрації;

|Користувач|

: Заповнює форму персональними даними нового користувача.
(Пошта, пароль, підтвердження пароля, ім'я) ;

|Система|

: Перевіряє дані на унікальність.;
note right #aaffaa

<font color=red><b> Можливо EX_00.

end note

: Перевіряє поля на заповненість. Перевіряє поля "пароль" 
та "підтвердження пароля" на збіг. ;

note right #aaffaa

<font color=red><b> Можливо EX_02.
<font color=red><b> Можливо EX_03.

end note

: Генерує посилання для підтвердження 
створення облікового запису
Надсилає лист на вказану пошту.;
note right #aaffaa

<font color=red><b> Можливо EX_01.

end note

|Користувач|

: Переходить за посиланням, та підтверджує створення
облікового запису. ;

note right #aaffaa

<font color=red><b> Можливо EX_04.

end note


|Система|

: Вносить відповідні записи до бази даних ;
note right #aaffaa

<font color=red><b> Можливо EX_05.

end note
|Користувач|
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml