 @startuml Forms Editing
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Редагування анкети з подальшим відсиланням результатів інтерв’юеру.
<font color=000 size=16><b>Учасники:</b> Адмінінстратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор має надати доступ інтерв'юеру для перегляду стану анкети.
<font color=000 size=16><b>Результат:</b> Інтерв'юер отримує сповіщення щодо змін в анкеті.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить у вкладку "Анкети";

|Система|
: Система надає створені анкети;

|Користувач|
: Адміністратор обирає та відкриває необхідну анкету;

: Після того, як анкета відкрилась, аміністратор обирає "Редагувати";

|Система|
: Система відкриває редактор анкет;

|Користувач|
: В редакторі анкет адміністратор вносить необхідні зміни;

: Натискає кнопку "Підтвердити";

|Система|
: Система зберігає зміни;

: Якщо поруч з пунктом "Сповістити інтерв'юерів" не поставити галочку,
     то зміни вступлять в силу без поінформованості інтерв'юерів;

: Якщо поставити галочку на сповіщенні,то адміністратор
  зможе додати короткий опис змін, після чого інтерв'юери
  даної анкети будуть сповіщені щодо внесених змін під
                час перегляду анкети;

: В залежності від параметру сповіщення система сповіщує/не сповіщує інтерв'юерів;

|Користувач|
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
