 @startuml Roles Simulation
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-4
<font color=000 size=16><b>Назва:</b>  Можливість "відігравати роль" як інтерв’юера, так і респондента.
<font color=000 size=16><b>Учасники:</b> Адмінінстратор, Система.
<font color=000 size=16><b>Передумови:</b> Адміністратор повинен перевіряти анкету, яка пройшла етап створення та готова до розсилання респондентам.
<font color=000 size=16><b>Результат:</b> Оцінка стану анкети, виявлення недоліків, відладка на різних етапах анкет.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор обирає необхідну анкету;

|Система|
: Система надає обрану анкету серед оступних анкетю;

|Користувач|
: Адміністратор обирає режим перегляду 
    анкети (нтерв’юер чи респондент);

|Система|
: Система відкриває обраний режим симуляції;

: При виборі режиму інтерв'юера відривається редактор анкет;

|Користувач|
: Після завершення редагування адміністратор має можливість
      перейти на вкладку "Розміщення анкети";

note left #aaffaa
  Вказуэться представлення даного опитування
    респондентам (посиланням, документом).
end note


|Система|
: Система надасть вибір представленя;

|Користувач|
: Після розміщення адміністратор може переглянути результати опитувань;

|Система|
: Система перейде на сторінку "Результати опитувань";

|Користувач|
: Адміністратор також має можливість перейти в режим респондента;

|Система|
: Система відкриває обраний режим симуляції;

|Користувач|
: В режимі респондента адміністратор може проходити опитування даного анкетування;

|Система|
: Система відкриє сторінку "пройти опитування";

|Користувач|
: Після аналізу роботи опитування адміністратор має змогу
  сповістити тех. підтримку та інтерв'юерів про зібрані
          результати роботи анкутування;

stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
