 @startuml Privileges&Ban
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-5
<font color=000 size=16><b>Назва:</b>  Маніпуляції з правами доступу користувачів.
<font color=000 size=16><b>Учасники:</b> Адмінінстратор, Система.
<font color=000 size=16><b>Передумови:</b> Користувачі мають бути в режимі інтерв'юера, аналітика.
<font color=000 size=16><b>Результат:</b> Зміна прав доступу до створення певної анкети.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Адміністратор переходить у вкладку "Анкети";

|Система|
: Система показує анкети, до яких причетний користувач;

|Користувач|
: Адміністратор обирає необхідну анкету;

|Система|
: Система відкриває режим редагування для адміністратора;

|Користувач|
: В режимі редагування адміністратор натискає
      кнопку "Переглянути користувачів";

|Система|
: Система надає аналітиків та інтерв'юерів,
      причетних до обраної анкети;

|Користувач|
: Адміністратор обирає одного з користувачів;

|Система|
: Система надає можливості взаємодії
    обраного користувача з анкетою;

|Користувач|
: Адміністратор ставить/знімає галочки поруч
  з пунктами перегляду, аналізу, редагування 
  анкети, також наявне поле "Забрати доступ";

note left #aaffaa
"Забрати доступ" - значить бан
(поруч можна вказати причину бану)
або ж видалення.
end note

|Система|
: Система реагує на обрані адміністратором
  права доступу та змінює можливості користувача;

|Користувач|
: Адміністратор може додати користувача (натисути "+");

|Система|
: Система відкриє вікно, де можна обрати режим
  користувача (інтерв'юер/аналітик/адміністратор)
  та вибрати права доступу для нього;

|Користувач|
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml
