
@startuml userRegistration

left header
<font color=000 size=18><b>Package:</b> Analyst

<font color=000 size=16><b>ID:</b> UC-4
<font color=000 size=16><b>Назва:</b> Формування звітності.
<font color=000 size=16><b>Учасники:</b> Користувач, Система.
<font color=000 size=16><b>Передумови:</b> Аналітики мають доступ до результатів опитувань, можуть переглядати їх.
<font color=000 size=16><b>Результат:</b>Дані анкетування надаються у файлі формату документу, де вказані результати анетувань.
<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Аналітик напискає кнопку "Сформувати звіт".;
|Система|
:Система видає вкладку, де обираються анкетування, які входять у звіт.;

|Користувач|

:Користувач обирає представлення і сортування відповідей (у відповідних списках-меню).;

:Після вибору потрібних анкет і параметрів аналітик натискае книпку 
"Далі (створити звіт)";
|Система|
:Система надає згенерований документ, в якому сформована 
титульна стовінка та пункти опитувань (їх представлення).;

|Користувач|
:Користувач може зберегти документ (в форматах .docx, .pdf, ...).;
stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml