@startuml interviewerPollCreating
left header
<font color=000 size=18><b>Package:</b> Interviewer

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Створення нового опитування.
<font color=000 size=16><b>Учасники:</b> Інтерв'юєр, Система.
<font color=000 size=16><b>Передумови:</b> Користувач повинен бути авторизований в системі та мати доступ до можливостей відповідного тарифу.
<font color=000 size=16><b>Результат:</b> Нове опитування створене.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: База даних не доступна.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Інтервьюєр переходить у розділ 
"Створити нове опитування".;
|Система|
: Система надає користувачу доступ до 
конструктора опитувань.;

|Користувач|

: Користувач створює необхідне йому 
опитування за допомогою конструктора. ;

: Користувач натискає кнопку "Створити". ;

|Система|

: Система створює відповідне опитування записує його до бази даних,
присвоює йому індекс та надає користувачу посилання на нього.;

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

: Система повідомляє користувача про 
успішне створення та публікацію його опитування, 
надає йому посилання на опитування. ;

|Користувач|

: Опитування створене, Інтервьюєр був повідомлений, 
має можливість працювати з опитуванням і надавати до нього доступ. ;


stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml