@startuml interviewerPollEditing
left header
<font color=000 size=18><b>Package:</b> Interviewer

<font color=000 size=16><b>ID:</b> UC-2
<font color=000 size=16><b>Назва:</b> Редагування опитувань.
<font color=000 size=16><b>Учасники:</b> Інтерв'юєр, Система.
<font color=000 size=16><b>Передумови:</b> Користувач має бути авторизований в системі, а також мати доступ до опитувань створених ним раніше.
<font color=000 size=16><b>Результат:</b> Користувач успішно редагує опитування, яке створив раніше.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: База даних не доступна.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач переходить у розділ "Мої опитування".;
|Система|
: Система надає користувачу доступ до бази даних 
опитувань, що були створені ним раніше.;

|Користувач|

: Користувач обирає потрібне йому опитування. ;

|Система|

: Система надає користувачу доступ до 
відповідного опитування.;

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

|Користувач|

: Користувач натискає кнопку "Редагувати". ;

|Система|

: Система відкриває відповідне опитування 
у конструкторі опитувань. ;

|Користувач|

: Користувач редагує вибране опитування 
відповідно до своїх потреб. ;

: Користувач натискає кнопку "Зберегти зміни". ;

|Система|

: Система зберігає зміни та оновлює 
інформацію щодо відповідного опитування. ;

: Система повідомляє користувача по успішне 
оновлення вибраного ним опитування. ;

|Користувач|

: Користувач отримує повідомлення про успішне 
оновлення вибраного ним опитування. ;


stop;

right footer


Системна динаміка. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer

@enduml